### ISSUE TITLE
Lexicon:  UI Needs Some Fixes

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#199]
We already went live with the Lexicon, the text  for "Help" need work The Search UI in Mystery Meat

[ ] Replace current text with

Welcome the Hindu Lexicon! Type any contiguous characters that you know are in a word. All the possible choices will appear. Use fewer characters if you do not know exactly how to spell the word. Use more if want to limit the choices. Gurudeva recommended studying a word by exploring its associated words. For example, take the word:

karma

and go on a word adventure by clicking other words that pop up.
 
You can permanently add word to My Words by clicking on the small bookmark. When you are in My Word, clicking the bookmark will delete that word from your saved list. To see all the words in the My Words list, you must empty the search field.

 [ ] Search:  Delete the horizontal bar
 [ ] Search: Enter a field bkgnd color: 10,70,80  (that is what I get in LC prototype, but please use that same color and background of the Header field and the footer field) No border, no dropshadow...
 [ ] Add a seach icon on the left of the search field. Make it white. (use font awesome). 
 
![2019-02-28_09-02-17](https://user-images.githubusercontent.com/3675722/53591586-70e87280-3b38-11e9-9ff6-281389fbf1e5.png)

**Comment by soapdog** [comment]
Aloha @Brahmanathaswami I've added the fixes you requested. I've changed the _add search icon from font-awesome_ because we're not using font awesome and also because adding font-awesome stuff to input fields is not easy. I've added a unicode magnifying glass as a placeholder though. 

Also, most of those changes are cosmetic changes that don't alter software behavior. None of these were bugs. Why the _urgent_ in the title? We should add urgent for stuff that is really problematic, stuff that if we don't do will cause us trouble.

**Comment by Brahmanathaswami** [comment]
OK I change the title of this issue, deleted the word "urgent" :-)
I pull, got  you changes

 web-modules/lexicon/build/bundle.js        | 77 +++++-------------------------
 web-modules/lexicon/src/Main.elm           |  6 +--
 web-modules/lexicon/src/Theme/Elements.elm | 30 +++---------
 3 files changed, 23 insertions(+), 90 deletions(-)
 if you do see the search engine field looking like the above (It doesn't really matter what you use for an icon.) It still look that same a before?

![2019-03-06_11-22-54](https://user-images.githubusercontent.com/3675722/53914850-a8589280-4002-11e9-9893-0ca712bb6c11.png)

**Comment by Brahmanathaswami** [comment]
This is still pending @soapdog

**Comment by Brahmanathaswami** [comment]
[ ] The search icon has no left or top margin. Is should be like the screen shot above
 [ ] The same for  entering a word, there should be a little margin on the left, 6 pixels would do. And make search box bigger by 10 point with the search icon and word you search for the same size . It too tight as it is. 
 [ ] is the search icon font awesome? It has a dark handle, the fontAwesome in complete white (like you see above.

 [ ] You have to typo the Help: the paragraph about word adventures end with "that pop up." 
That last paragraph is about adding to My Words. But you have no space and the next paragraph starts.  You need  blank line: 

"...that pop up.</p>

<p>You can permanenty add words..."

A full blank line word by good.

**Comment by soapdog** [comment]
* change search input placeholder to "type to search"

**Comment by soapdog** [comment]
fixed.

**Comment by Brahmanathaswami** [comment]
You can fix the input box :-) 
1) take away the space in front of the place holder.

```
<div class="_24f34a5">
<input class="_ddbecf27" id="search-box" placeholder="type to search">
</div>
```
2) add the following two lines to the CSS

 ```
   line-height: 2;
    padding-left: 20px;

```
normallize.css: line 168
```
button, input {
    overflow: visible;
    line-height: 2;
    padding-left: 20px;
```

**Comment by bwmilby** [comment]
Here is the look on an iPhone X (simulator).  The grey area at the top and bottom is part of the browser widget.  This screenshot does not show the rounded corners nor the notch.  If you grab above the search field, you can drag the background color into the grey areas.  I'm not sure if this is the intended look for this device.
![image](https://user-images.githubusercontent.com/29169921/60379651-9614c100-9a04-11e9-8a80-f79de40676ed.png)

**Comment by Brahmanathaswami** [comment]
@bwmilby Ah yes, Need a fix, this is HTML5 done in Elm by Andre. He will have to fix it: 

 [ ] Get the blue background to fill the entire screen top notch area and bottom swipe up. 
 [ ] These areas do not need any live content, just the background
 [ ] If get a definition that is longer than the screen, I should appear above the top tabs or below the book nav bar. Like this screen shot. should not be happening.

![IMG_1159](https://user-images.githubusercontent.com/3675722/60384967-bef67f80-9a1f-11e9-82d0-f47792a3f9e0.PNG)

**Comment by bwmilby** [comment]
One solution would be to use the safe margin code to reduce the size of the browser rect.  I set a background color on the card already since I thought that was the issue.  I’ll try that and see what Elm does with the render.

**Comment by soapdog** [comment]
setting up my current machine to work on it... will ping back

**Comment by soapdog** [comment]
There is something odd going on. @Brahmanathaswami and @bwmilby did you folks deleted my code from the repo? The content [from this commit](https://github.com/Himalayan-Academy/Siva-Siva-App/commit/aef4f844d0f045d4072a25778bbbb019e8ef037c) is not on the current nightly like it should. Did someone overwrote my fixes?

**Comment by soapdog** [comment]
The screenshots @bwmilby and @Brahmanathaswami are not from the version that contained the fixes I made. For example, that is not the search bar from the fixes. I suspect someone accidentally overwrote the fixes with an old copy. I'm picking it from git history and will push it back with new fixes shortly.

**Comment by soapdog** [comment]
@Brahmanathaswami  
> ```
> button, input {
>     overflow: visible;
>     line-height: 2;
>     padding-left: 20px;
> ```

Padding can't be used to move the placeholder to the right, it doesn't work, thats why I added spaces in front of it.

**Comment by Brahmanathaswami** [comment]
button, input {
    overflow: visible;
    line-height: 2;
    padding-left: 20px;
This worked be for when you had the search icon, in the web developer...

But now you have change it to "placeholder" and he icon is gone. Why? did you replace the button/icon?  now you don't have margin on the bottom.  We can about it on

**Comment by soapdog** [comment]
Go with:

```
element {
    line-height: 1.5em;
    padding-left: 15px;
}
```

Go with magnifying glass.

**Comment by soapdog** [comment]
Fixed. Please review. ;-)

**Comment by Brahmanathaswami** [comment]
I am still seeing the "type to search" and not a magnifying glass.  Have emptied my cache...
![2019-07-12_11-11-22](https://user-images.githubusercontent.com/3675722/61158991-47503800-a496-11e9-924c-312b6c2ae787.png)

**Comment by soapdog** [comment]
I forgot to upload to the online folder. Just did that:

http://dev.himalayanacademy.com/media/apps/lexicon/app/

**Comment by Brahmanathaswami** [comment]
Look good.
Do a pull on nightly
merge with the Lexicon branch
then merge back the Lexicon into nightly.

**Comment by Brahmanathaswami** [comment]
- [ ] the Home icon at the bottom left does not to home
- [ ] The settings icon does nothing
- [ ] I cannot select a word and get a definition

**Comment by Brahmanathaswami** [comment]
close for now...
